const ACTION_TYPES = {
  ADD_BUTTONS_LIST: 'ADD_BUTTONS_LIST',
  CLICK_ON_BUTTON: 'CLICK_ON_BUTTON',
  TOGGLE_DISABLE: 'TOGGLE_DISABLE',
  SELECT_ITEM: 'SELECT_ITEM',
  ADD_COMMENTS: 'ADD_COMMENTS'
};

export default ACTION_TYPES;
